CLASS zbp_i_zmm_milkcoll_miro DEFINITION PUBLIC ABSTRACT
FINAL FOR BEHAVIOR OF zi_zmm_milkcoll_miro.

PUBLIC SECTION.
    CLASS-DATA mapped_miro TYPE RESPONSE FOR MAPPED i_supplierinvoicetp.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.



CLASS ZBP_I_ZMM_MILKCOLL_MIRO IMPLEMENTATION.
ENDCLASS.
