CLASS zbp_i_zmm_milkcoll DEFINITION
PUBLIC
ABSTRACT
FINAL FOR BEHAVIOR OF zi_zmm_milkcoll.

PUBLIC SECTION.
    CLASS-DATA mapped_purchase_order TYPE RESPONSE FOR MAPPED i_purchaseordertp_2.
    CLASS-DATA mapped_material_document TYPE RESPONSE FOR MAPPED I_MATERIALDOCUMENTTP.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.



CLASS ZBP_I_ZMM_MILKCOLL IMPLEMENTATION.
ENDCLASS.
