function z_fetch_milk_rate.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IV_PLANT) TYPE  WERKS_D
*"     REFERENCE(IV_SLOC) TYPE  ZMM_MILKRATECARD-SLOC
*"     REFERENCE(IV_LIFNR) TYPE  LIFNR
*"     REFERENCE(IV_MILKTYPE) TYPE  C
*"     REFERENCE(IV_MATNR) TYPE  MATNR
*"     REFERENCE(IV_DATE) TYPE  DATUM
*"     REFERENCE(IV_FAT) TYPE  MENGE_D
*"     REFERENCE(IV_SNF) TYPE  MENGE_D
*"  EXPORTING
*"     REFERENCE(EV_RATE) TYPE  ZMM_MILKRATECARD-RATE
*"     REFERENCE(EV_BASERATE) TYPE  ZMM_MILKRATECARD-BASE_RATE
*"     REFERENCE(EV_INCENTIVE) TYPE  ZMM_MILKRATECARD-INCENTIVE
*"     REFERENCE(EV_COMMISION) TYPE  ZMM_MILKRATECARD-COMMISION
*"     REFERENCE(EV_TRANSPORT) TYPE  ZMM_MILKRATECARD-TRANSPORT
*"----------------------------------------------------------------------
  SELECT * FROM ZMM_MILKRATECARD
  WHERE PLANT  = @IV_PLANT
  AND   SLOC   = @IV_SLOC
  AND   VENDOR = @IV_LIFNR
  AND   MILK_TYPE = @IV_MILKTYPE
  AND   MATNR  = @IV_MATNR
  AND   EFFDATE LE @IV_DATE
  AND   FAT    = @IV_FAT
  AND   SNF    = @IV_SNF
  INTO TABLE @DATA(LT_MILKRATE).
IF LT_MILKRATE[] IS INITIAL.

  SELECT * FROM ZMM_MILKRATECARD
  WHERE PLANT  = @IV_PLANT
  AND   SLOC   = @IV_SLOC
  AND   VENDOR IS INITIAL
  AND   MILK_TYPE = @IV_MILKTYPE
  AND   MATNR  = @IV_MATNR
  AND   EFFDATE LE @IV_DATE
  AND   FAT    = @IV_FAT
  AND   SNF    = @IV_SNF
  INTO TABLE @LT_MILKRATE.
IF LT_MILKRATE[] IS INITIAL.

*  SELECT * FROM ZMM_MILKRATECARD
*  WHERE PLANT  = @IV_PLANT
**  AND   SLOC   = @IV_SLOC
**  AND   VENDOR = @IV_LIFNR
*  AND   MILK_TYPE = @IV_MILKTYPE
*  AND   MATNR  = @IV_MATNR
*  AND   EFFDATE LE @IV_DATE
*  AND   FAT    = @IV_FAT
*  AND   SNF    = @IV_SNF
*  INTO TABLE @LT_MILKRATE.
ENDIF.
ENDIF.


IF LT_MILKRATE[] IS NOT INITIAL.
 SORT LT_MILKRATE BY EFFDATE DESCENDING.
 READ TABLE LT_MILKRATE INTO DATA(LS_MILKRATE) INDEX 1.
 EV_RATE      = LS_MILKRATE-RATE.
 EV_BASERATE  = LS_MILKRATE-BASE_RATE.
 EV_INCENTIVE = LS_MILKRATE-INCENTIVE.
 EV_COMMISION = LS_MILKRATE-COMMISION.
 EV_TRANSPORT = LS_MILKRATE-TRANSPORT.
ENDIF.

ENDFUNCTION.
