CLASS zbp_i_billinginv DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_billinginv.

PUBLIC SECTION.
    CLASS-DATA mapped_IRN TYPE RESPONSE FOR MAPPED zi_billinginv.
ENDCLASS.



CLASS ZBP_I_BILLINGINV IMPLEMENTATION.
ENDCLASS.
