CLASS zbp_i_accdoc DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_accdoc.
PUBLIC SECTION.
CLASS-DATA mapped_accdoc TYPE RESPONSE FOR MAPPED i_journalentrytp.

ENDCLASS.



CLASS ZBP_I_ACCDOC IMPLEMENTATION.
ENDCLASS.
