CLASS zbp_i_sales_order_header DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF
zi_sales_order_header.
PUBLIC SECTION.
CLASS-DATA mapped_sales_order TYPE RESPONSE FOR MAPPED i_salesordertp.
ENDCLASS.



CLASS ZBP_I_SALES_ORDER_HEADER IMPLEMENTATION.
ENDCLASS.
