CLASS zbp_i_so DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_so.

PUBLIC SECTION.
CLASS-DATA mapped_sales_order TYPE RESPONSE FOR MAPPED i_salesordertp.
ENDCLASS.



CLASS ZBP_I_SO IMPLEMENTATION.
ENDCLASS.
