CLASS zbp_i_wb_view DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_wb_view.

PUBLIC SECTION.
    CLASS-DATA mapped_material_document TYPE RESPONSE FOR MAPPED I_MATERIALDOCUMENTTP.
ENDCLASS.



CLASS ZBP_I_WB_VIEW IMPLEMENTATION.
ENDCLASS.
