CLASS zcl_wrap_get_route DEFINITION
  PUBLIC
  FINAL
  CREATE PRIVATE .

  PUBLIC SECTION.
    INTERFACES zif_wrap_get_route.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_WRAP_GET_ROUTE IMPLEMENTATION.


  METHOD zif_wrap_get_route~get_data.

  TYPES : BEGIN OF TY_ROUTE,
           ROUTE TYPE i_route-route,
           RouteName(40) type C,
          END OF TY_ROUTE.

  TYPES : T_ROUTE TYPE STANDARD TABLE OF TY_ROUTE WITH KEY ROUTE.

*      SELECT ROUTE, \_TEXT[ ONE TO MANY WHERE LANGUAGE = 'E' ]-ROUTENAME FROM I_ROUTE
*      WHERE ROUTE NE ''
*      INTO TABLE @T_ROUTE.

  ENDMETHOD.
ENDCLASS.
